// <auto-generated />
using System;
using AdminTareas.Datos.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminTareas.Datos.Migrations
{
    [DbContext(typeof(AdminTareaContext))]
    partial class AdminTareaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("AdminTareas.Modelos.Entidades.EstadoTarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EstadoTareas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Tarea pendiente de iniciar",
                            Nombre = "PENDIENTE"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Tarea en proceso",
                            Nombre = "EN_PROCESO"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Tarea completada",
                            Nombre = "FINALIZADA"
                        });
                });

            modelBuilder.Entity("AdminTareas.Modelos.Entidades.PrioridadTarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PrioridadTareas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Prioridad alta",
                            Nombre = "ALTA"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Prioridad media",
                            Nombre = "MEDIA"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Prioridad baja",
                            Nombre = "BAJA"
                        });
                });

            modelBuilder.Entity("AdminTareas.Modelos.Entidades.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCompromiso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
